---
title: "STA 631 Statistical Modelling About Project and Dataset overview"
site: distill::distill_website
---

### Description about the Project

Hotel booking cancellation prediction is a crucial task for hotel management to optimize their operations, revenue, and customer satisfaction. By accurately predicting which bookings are likely to be canceled, hotels can take proactive measures to minimize the impact, such as overbooking rooms, offering incentives to retain customers, or adjusting pricing strategies.

The dataset provides valuable insights into various factors that may influence booking cancellations, such as lead time, arrival date, booking channel, customer demographics, and special requests. By analyzing this data and building predictive models, we aim to identify patterns and relationships that can help predict whether a booking is likely to be canceled.

### Overview of the Dataset

Dataset has nearly 119390 observations and 32 columns

1. hotel: Type of hotel (Resort Hotel or City Hotel).
2. is_canceled: Binary variable indicating whether the booking was canceled (1) or not (0).
3. lead_time: Number of days between booking and arrival.
4. arrival_date_year: Year of arrival.
5. arrival_date_month: Month of arrival.
6. arrival_date_week_number: Week number of arrival.
7. arrival_date_day_of_month: Day of the month of arrival.
8. stays_in_weekend_nights: Number of weekend nights (Saturday or Sunday) the guest stayed.
9. stays_in_week_nights: Number of weekday nights (Monday to Friday) the guest stayed.
10. adults: Number of adults.
11. children: Number of children.
12. babies: Number of babies.
13. meal: Type of meal booked (e.g., Bed & Breakfast, Half Board, Full Board).
14. country: Country of origin of the guest.
15. market_segment: Market segment designation (e.g., Online TA, Offline TA/TO, Direct).
16. distribution_channel: Booking distribution channel (e.g., Online Travel Agents, Direct).
17. is_repeated_guest: Binary variable indicating whether the guest is a repeated guest (1) or not (0).
18. previous_cancellations: Number of previous bookings canceled by the guest.
19. previous_bookings_not_canceled: Number of previous bookings not canceled by the guest.
20. reserved_room_type: Type of room reserved.
21. assigned_room_type: Type of room assigned.
22. booking_changes: Number of changes made to the booking.
23. deposit_type: Type of deposit made for the booking (e.g., No Deposit, Non-Refundable).
24. agent: ID of the travel agency that made the booking.
25. company: ID of the company/entity that made the booking.
26. days_in_waiting_list: Number of days the booking was on the waiting list before it was confirmed.
27. customer_type: Type of customer (e.g., Transient, Contract, Group).
28. adr: Average Daily Rate (average revenue per room).
29. required_car_parking_spaces: Number of parking spaces required by the guest.
30. total_of_special_requests: Number of special requests made by the guest.
31. reservation_status: Reservation last status (e.g., Check-Out, Canceled).
32. reservation_status_date: Date at which the last status was set.





